### ISSUE TITLE
Cannot launch plug

### ISSUE THREAD

**Issue by lenemter** [elementary/switchboard-plug-pantheon-shell#333]
### What Happened?

Probably caused by #331 

Switchboard crashes with message:

```
**
GLib:ERROR:../../../glib/gvarianttypeinfo.c:164:g_variant_type_info_check: assertion failed: (info->alignment == 0 || info->alignment == 1 || info->alignment == 3 || info->alignment == 7)
Bail out! GLib:ERROR:../../../glib/gvarianttypeinfo.c:164:g_variant_type_info_check: assertion failed: (info->alignment == 0 || info->alignment == 1 || info->alignment == 3 || info->alignment == 7)
Aborted
```

### Steps to Reproduce

1. Open plug

### Expected Behavior

No crash

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
GLib:ERROR:../../../glib/gvarianttypeinfo.c:164:g_variant_type_info_check: assertion failed: (info->alignment == 0 || info->alignment == 1 || info->alignment == 3 || info->alignment == 7)
Bail out! GLib:ERROR:../../../glib/gvarianttypeinfo.c:164:g_variant_type_info_check: assertion failed: (info->alignment == 0 || info->alignment == 1 || info->alignment == 3 || info->alignment == 7)
Aborted
```

**Comment by lenemter** [comment]
The same changes in GTK4 plug don't cause crash

**Comment by jeremypw** [comment]
Hmm,  I've test #331 on both OS7 and OS6.1 without crashes.  Can you get a backtrace from `gdb`  - doesn't always work with plugs though?

**Comment by lenemter** [comment]
Not sure how to do this, but that's what I got

```
**
GLib:ERROR:../../../glib/gvarianttypeinfo.c:164:g_variant_type_info_check: assertion failed: (info->alignment == 0 || info->alignment == 1 || info->alignment == 3 || info->alignment == 7)
Bail out! GLib:ERROR:../../../glib/gvarianttypeinfo.c:164:g_variant_type_info_check: assertion failed: (info->alignment == 0 || info->alignment == 1 || info->alignment == 3 || info->alignment == 7)

Thread 1 "io.elementary.s" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737318414976) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737318414976) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737318414976) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737318414976, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff700f476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff6ff57f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7e83b57 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff7edd6ff in g_assertion_message_expr () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff7efde56 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff7efdeff in g_variant_type_info_get_type_string () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff7ef87ad in g_variant_is_of_type () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff7d7f2a3 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#11 0x00007ffff7c41d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff7c5db76 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff7c5f554 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff7c5f7a3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff7c4c284 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff7c52f8a in g_object_notify () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff75e868a in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff7c5eb66 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff7c5f7a3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff75e86f5 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff7c5f640 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff7c5f7a3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff76843f8 in gtk_toggle_button_set_active () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff7c51be6 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff7c53e14 in g_object_setv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff7c53edf in g_object_set_property () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff7d805d3 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#28 0x00007ffff7d899f7 in g_settings_bind_with_mapping () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#29 0x00007fffe89db545 in  () at /usr/lib/x86_64-linux-gnu/switchboard/personal/libpantheon-desktop.so
#30 0x00007ffff7c5217e in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007ffff7c531ad in g_object_new_with_properties () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007ffff7c53cb1 in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007fffe89de3d4 in  () at /usr/lib/x86_64-linux-gnu/switchboard/personal/libpantheon-desktop.so
#34 0x00007ffff7fa2ac9 in switchboard_plug_get_widget (self=0x7fffd800e460) at ../lib/Plug.vala:90
#35 0x0000555555560fc5 in __lambda8_ (_data2_=0x555555738da0) at ../src/Application.vala:368
#36 0x0000555555561352 in ___lambda8__gsource_func (self=0x555555738da0) at /home/lenemter/Projects/switchboard/build/Application.c:2619
#37 0x00007ffff7ebac24 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff7f0f6f8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007ffff7eba293 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007ffff7583cfd in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#41 0x00005555555603b9 in switchboard_switchboard_app_real_activate (base=0x55555558d140) at ../src/Application.vala:322
--Type <RET> for more, q to quit, c to continue without paging--
#42 0x00007ffff7c5f640 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#43 0x00007ffff7c5f7a3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#44 0x00007ffff7d6da38 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#45 0x00007ffff7d6dc16 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#46 0x000055555555d2ca in switchboard_main (args=0x7fffffffddd8, args_length1=1) at ../src/Application.vala:25
#47 0x000055555555d311 in main (argc=1, argv=0x7fffffffddd8) at ../src/Application.vala:23
```

**Comment by jeremypw** [comment]
OK, thanks. It does look like it is the bidirectional binding causing it.  Maybe a race of some kind during startup which only causes a crash on some machines :shrug:   I'll see if I can spot anything in the code that might cause this.

**Comment by jeremypw** [comment]
@lenemter Could you try #334 to see if it makes a difference on you machine?  Just reorders the construct clauses and puts in some explicit null returns in the bindings.

**Comment by jeremypw** [comment]
Not exactly sure why the linked PR fixes the issue but as it cures the problem for you and does not cause any regressions for me, I'll close this.  If anyone else still experiences this problem please re-open.
